apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetest
  labels:
    app: nodetest
spec:
  selector:
    matchLabels:
      app: nodetest
  replicas: 4
  template:
    metadata:
      labels:
        app: nodetest
    spec:
      containers:
      - name: nodetest
        image: ejbest/nodetest
        ports:
        - containerPort: 8080
       # command: ["top"]
       