apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: wtest
  name: wtest
spec:
  ports:
    - name: "80"
      port: 8080
      targetPort: 80
status:
  loadBalancer: {}
